---
name: Bug Report
about: Report a bug or issue with the site
title: "[BUG] "
labels: ["bug"]
assignees: []

---

## Bug Description
<!-- A clear and concise description of what the bug is -->

## Steps to Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected Behavior
<!-- What you expected to happen -->

## Actual Behavior
<!-- What actually happened -->

## Screenshots
<!-- If applicable, add screenshots to help explain your problem -->

## Environment
- **Browser**: [e.g., Chrome, Firefox, Safari]
- **OS**: [e.g., Windows, macOS, Linux]
- **Device**: [e.g., Desktop, Mobile]

## Additional Context
<!-- Add any other context about the problem here -->